### ISSUE TITLE
Seite aktualisiert nicht

### ISSUE THREAD

**Issue by SETobiasWuest** [RushMaster007/HtmlMultiplayer#4]

**Comment by SETobiasWuest** [comment]
Verbindung zum WebSocket kann nicht hergestellt werden

![image](https://github.com/RushMaster007/HtmlMultiplayer/assets/145535123/e0c1ffb7-a77b-4da6-ba3c-32b70461e0a5)

**Comment by RushMaster007** [comment]
in arbeit
